### ISSUE TITLE
add descriptions

### ISSUE THREAD

**Issue by lukeed** [guuibayer/awesome-inferno#1]
Each item should have a description alongside its link, like [this](https://github.com/brillout/awesome-react-components).

Often times a title alone isn't enough to describe, or there may be duplicate titles.

**Comment by iamgbayer** [comment]
Agree with you, i saw that you have already opened a pull request for this, thanks!

**Comment by lukeed** [comment]
I got started on the boilerplate section only 😄 

I figure that there's no need to keep repeating `Inferno` so I've removed its mention every time.

**Comment by iamgbayer** [comment]
Just like in [this ](https://github.com/brillout/awesome-react-components) example you have shown, names are repeated, like the name of the repository itself
